llms:
  nim_llm:
    _type: nim
    model_name: nvidia/nemotron-3-nano-30b-a3b
    base_url: https://integrate.api.nvidia.com/v1
    api_key: dummy
    max_tokens: 4096

function_groups:
  ## TODO

workflow:
  ## TODO
